import { eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { fieldReports,reportPhotos,users } from "../../../db/schema";
import { blobError, putReportBlob, readReportBlob } from "../../blob-storage";
import { getChatGPTUser } from "../../chatgpt-auth";

export const maxDuration=60;
export async function POST(request:Request){
  const auth=await getChatGPTUser();if(!auth)return Response.json({error:"Sign in required"},{status:401});if(!process.env.BLOB_READ_WRITE_TOKEN)return Response.json({error:"Vercel Blob storage is unavailable"},{status:500});const db=getDb();const [user]=await db.select().from(users).where(eq(users.authUserId,auth.userId)).limit(1);if(!user)return Response.json({error:"Profile unavailable"},{status:403});const form=await request.formData();const reportId=Number(form.get("reportId"));const [report]=await db.select().from(fieldReports).where(eq(fieldReports.id,reportId)).limit(1);if(!report)return Response.json({error:"Report not found"},{status:404});const files=form.getAll("files").filter((item):item is File=>item instanceof File);if(!files.length)return Response.json({error:"Choose at least one image"},{status:400});if(files.length>10)return Response.json({error:"Maximum 10 images per upload"},{status:400});const saved=[];
  for(const file of files){if(!file.type.startsWith("image/")||file.size>8_000_000)return Response.json({error:"Images must be under 8 MB each"},{status:400});const key=`reports/${reportId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;let blob;try{blob=await putReportBlob(key,file,file.type)}catch(cause){return Response.json({error:blobError(cause)},{status:500})}const [photo]=await db.insert(reportPhotos).values({reportId,objectKey:blob.url,fileName:file.name,contentType:file.type,sizeBytes:file.size,uploadedBy:user.id}).returning();saved.push(photo)}return Response.json({photos:saved},{status:201});
}
export async function GET(request:Request){const auth=await getChatGPTUser();if(!auth)return new Response("Sign in required",{status:401});const id=Number(new URL(request.url).searchParams.get("id"));const [photo]=await getDb().select().from(reportPhotos).where(eq(reportPhotos.id,id)).limit(1);if(!photo)return new Response("Not found",{status:404});const object=await readReportBlob(photo.objectKey);if(!object)return new Response("Not found",{status:404});return new Response(object.body,{headers:{"content-type":photo.contentType,"cache-control":"private, max-age=300"}})}
